# Generated by Django 3.2.12 on 2023-11-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema__seguranca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(upload_to='Alunos/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(upload_to='Funcionarios/'),
        ),
        migrations.CreateModel(
            name='FotoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Bloqueado/')),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sistema__seguranca.bloqueado')),
            ],
        ),
    ]
