# Generated by Django 3.2.12 on 2023-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema__seguranca', '0002_auto_20231119_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='foto',
        ),
        migrations.AlterField(
            model_name='fotobloqueado',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
